### ISSUE TITLE
No results returned from Web Search

### ISSUE THREAD

**Issue by Czupryn013** [samnodehi/n8n-nodes-duckduckgo#7]
Sadly the search web node seems to not work correctly. No matter the query it always retruns empty results as seen in the screenshot below:

<img width="1149" height="697" alt="Image" src="https://github.com/user-attachments/assets/40e84d0e-7559-4e36-b15b-4c621a445e09" />

I've tried changing the locale, language and inputing a hard-coded query but to no effect

**Comment by samnodehi** [comment]
Hi,

Thanks for raising this issue.

This was a confirmed bug that has been resolved in version 30.0.4, as shown in the commit history below:
<img width="1234" height="211" alt="Image of commit log showing the fix" src="https://github.com/user-attachments/assets/f9b66ea6-cca9-4338-86d2-c7a09635133a" />

Could you please update your instance to the latest version and verify if the problem is solved?

I have tested all the Search nodes on the latest version, and they are now working correctly and returning results as expected.

Web Search:
<img width="1699" height="828" alt="Web Search working correctly" src="https://github.com/user-attachments/assets/44c4f8de-a18d-4a8a-9607-d30d71f643b6" />

Image Search:
<img width="1699" height="840" alt="Image Search working correctly" src="https://github.com/user-attachments/assets/ee6f5982-cc2e-485f-911d-44bda72cebf2" />

News Search:
<img width="1701" height="839" alt="News Search working correctly" src="https://github.com/user-attachments/assets/fa5424e0-6228-49ae-81a8-24144e65c203" />

Video Search:
<img width="1701" height="828" alt="Video Search working correctly" src="https://github.com/user-attachments/assets/953dbd22-0014-4f38-89a3-8a6d3f1f8142" />

If the issue persists after the update, please let us know.

Thanks!

**Comment by Czupryn013** [comment]
The issue persists. After the update it did in fact work once, but then stopped again:

<img width="1435" height="351" alt="Image" src="https://github.com/user-attachments/assets/44ef6d41-7e16-41ed-84f1-fe5faa14743f" />

I've tried multiple queries and locale settings:

<img width="1267" height="873" alt="Image" src="https://github.com/user-attachments/assets/c932ff18-987b-4a63-81e4-bf65de8a5bbf" />

**Comment by samnodehi** [comment]
Hi Piotr,
Thank you very much for your follow-up.
In some cases, to fully apply changes after an update, it may be necessary to create a new node so that the node accepts the new update. I tested again with the same information you provided and I will send you the image of the result.

<img width="1672" height="838" alt="Image" src="https://github.com/user-attachments/assets/d9d9efaa-8c2d-4ad8-934c-7bb50cb0d1c3" />

Also, given that I use this node in my own projects, I use it several times a day.

Thank you,
Sam
